import { Sparkles } from "lucide-react";

import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import type { SoapReport } from "@/lib/types";

function SoapSection({
  letter,
  title,
  children,
  className,
}: {
  letter: "S" | "O" | "A" | "P";
  title: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <section
      className={cn(
        "grid grid-cols-1 gap-3 py-5 md:grid-cols-[140px_1fr] md:gap-6",
        className
      )}
    >
      <div className="flex md:flex-col">
        <span
          className="flex h-9 w-9 items-center justify-center rounded-md bg-muted text-[15px] font-semibold text-primary"
          aria-hidden="true"
        >
          {letter}
        </span>
        <h3 className="ml-3 self-center text-[13.5px] font-semibold md:ml-0 md:mt-2.5 md:self-start">
          {title}
        </h3>
      </div>
      <div className="text-[13.5px] leading-relaxed text-foreground/85">
        {children}
      </div>
    </section>
  );
}

function Kv({ k, v }: { k: string; v: string }) {
  return (
    <div className="grid grid-cols-[110px_1fr] gap-3 py-1.5">
      <dt className="text-[12.5px] font-medium uppercase tracking-wider text-muted-foreground">
        {k}
      </dt>
      <dd className="text-[13.5px] text-foreground/90">{v}</dd>
    </div>
  );
}

export function SoapPanel({ soap }: { soap: SoapReport }) {
  return (
    <Card className="gap-0 py-0">
      <CardContent className="px-6 py-1">
        <SoapSection letter="S" title="Subjective">
          <p className="mb-3 font-medium text-foreground">
            {soap.subjective.cc}
          </p>
          <p>{soap.subjective.hpi}</p>
          <dl className="mt-4 divide-y divide-border">
            <Kv k="PMH" v={soap.subjective.pmh} />
            <Kv k="Meds" v={soap.subjective.meds} />
            <Kv k="Allergies" v={soap.subjective.allergies} />
            <Kv k="Social" v={soap.subjective.social} />
          </dl>
        </SoapSection>

        <Separator />

        <SoapSection letter="O" title="Objective">
          <p className="mb-3 font-medium text-foreground">
            {soap.objective.vitalsNote}
          </p>
          <dl className="grid grid-cols-2 gap-x-6 gap-y-1">
            <Kv k="BP" v={soap.objective.bp} />
            <Kv k="Temp" v={soap.objective.temp} />
            <Kv k="Weight" v={soap.objective.weight} />
          </dl>
        </SoapSection>

        <Separator />

        <SoapSection letter="A" title="Assessment">
          <p className="mb-2 font-medium text-foreground">
            {soap.assessment.primary}
          </p>
          <p className="mb-3">{soap.assessment.rationale}</p>
          <div>
            <p className="mb-2 text-[12.5px] font-medium uppercase tracking-wider text-muted-foreground">
              Differentials considered
            </p>
            <ul className="flex flex-col gap-1">
              {soap.assessment.differentials.map((d, i) => (
                <li
                  key={i}
                  className="flex items-start gap-2 text-[13.5px]"
                >
                  <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-muted-foreground/40" />
                  <span>{d}</span>
                </li>
              ))}
            </ul>
          </div>
        </SoapSection>

        <Separator />

        <SoapSection letter="P" title="Plan">
          <ol className="flex flex-col gap-2">
            {soap.plan.map((p, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-muted font-mono text-[11px] font-medium tabular-nums text-muted-foreground">
                  {i + 1}
                </span>
                <span>{p}</span>
              </li>
            ))}
          </ol>
        </SoapSection>
      </CardContent>

      <div className="flex items-center justify-between rounded-b-xl border-t border-border bg-muted/30 px-6 py-3">
        <div className="inline-flex items-center gap-1.5 text-[12px] text-muted-foreground">
          <Sparkles className="h-3 w-3" />
          Generated by triage AI · 2 minutes ago · Model v0.4.2
        </div>
        <div className="hidden text-[12px] text-muted-foreground md:block">
          Always verify against patient context.
        </div>
      </div>
    </Card>
  );
}
